"""add dwc species

Revision ID: 8022291ae0f4
Revises: deeb676c33a8
Create Date: 2026-03-16 13:23:58.256765

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '8022291ae0f4'
down_revision = 'deeb676c33a8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
