"""Initial models

Revision ID: 80e9cad03427
Revises: 
Create Date: 2025-12-31 12:06:05.320433

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import uniback.persistence.base


# revision identifiers, used by Alembic.
revision = '80e9cad03427'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ub_object_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', uniback.persistence.base.GUID(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('ub_fs_storages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', uniback.persistence.base.GUID(length=32), nullable=False),
    sa.Column('storage_type', sa.String(length=10), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('ub_hierarchy_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', uniback.persistence.base.GUID(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('ub_sa_annotation_form_item',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('annotation_type', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('default_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('standard', sa.Boolean(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'standard', 'annotation_type', name='ub_sa_annotation_form_item_c1')
    )
    op.create_table('ub_sa_auth_authenticators',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', uniback.persistence.base.GUID(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('validation_endpoint', sa.String(length=1024), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('ub_sa_auth_authorizables',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', uniback.persistence.base.GUID(length=32), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('authorizable_type_id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('ub_sa_auth_functions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', uniback.persistence.base.GUID(length=32), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('can_execute_rule', sa.String(length=1024), nullable=True),
    sa.Column('acl_expression_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('ub_sa_auth_permission_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', uniback.persistence.base.GUID(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ub_sa_task_statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', uniback.persistence.base.GUID(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ub_sa_task_system_processes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', uniback.persistence.base.GUID(length=32), nullable=False),
    sa.Column('description', sa.String(length=80), nullable=True),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_singleton', sa.Boolean(), nullable=True),
    sa.Column('is_running', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ub_hierarchies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', uniback.persistence.base.GUID(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=True),
    sa.Column('h_type_id', sa.Integer(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['h_type_id'], ['ub_hierarchy_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('ub_sa_annotation_form_field',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('range', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('view_type', sa.String(length=32), nullable=True),
    sa.Column('schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['ub_sa_annotation_form_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ub_sa_annotation_form_item_object_types',
    sa.Column('form_item_id', sa.BigInteger(), nullable=False),
    sa.Column('object_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['form_item_id'], ['ub_sa_annotation_form_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_type_id'], ['ub_object_types.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('form_item_id', 'object_type_id')
    )
    op.create_table('ub_sa_annotation_form_template',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['ub_sa_annotation_form_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ub_sa_auth_functions_rels',
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('relation_type', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['ub_sa_auth_functions.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['ub_sa_auth_functions.id'], ),
    sa.PrimaryKeyConstraint('source_id', 'target_id', 'relation_type')
    )
    op.create_table('ub_sa_auth_groups',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['ub_sa_auth_authorizables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ub_sa_auth_identities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('can_login', sa.Boolean(), nullable=False),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('deactivation_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['ub_sa_auth_authorizables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ub_sa_auth_obj_types_perm_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('object_type_id', sa.Integer(), nullable=False),
    sa.Column('permission_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['object_type_id'], ['ub_object_types.id'], ),
    sa.ForeignKeyConstraint(['permission_type_id'], ['ub_sa_auth_permission_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_type_id', 'permission_type_id', name='ub_sa_auth_obj_types_perm_types_c1')
    )
    op.create_table('ub_sa_auth_organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['ub_sa_auth_authorizables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ub_sa_auth_permissions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', uniback.persistence.base.GUID(length=32), nullable=False),
    sa.Column('object_type', sa.Integer(), nullable=False),
    sa.Column('object_uuid', uniback.persistence.base.GUID(length=32), nullable=True),
    sa.ForeignKeyConstraint(['object_type'], ['ub_object_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('object_uuid', 'object_type', name='ub_sa_auth_permissions_c1')
    )
    op.create_table('ub_sa_auth_roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['ub_sa_auth_authorizables.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ub_sa_task_instances',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', uniback.persistence.base.GUID(length=32), nullable=False),
    sa.Column('params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('finalization_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('log', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['status'], ['ub_sa_task_statuses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ub_functional_objects',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('uuid', uniback.persistence.base.GUID(length=32), nullable=False),
    sa.Column('object_type_id', sa.Integer(), nullable=True),
    sa.Column('native_id', sa.BigInteger(), nullable=True),
    sa.Column('native_table', sa.String(length=80), nullable=True),
    sa.Column('owner_id', sa.Integer(), nullable=True),
    sa.Column('creation_time', sa.DateTime(), nullable=False),
    sa.Column('entity_update_time', sa.DateTime(), nullable=True),
    sa.Column('ts_vector_update_time', sa.DateTime(), nullable=True),
    sa.Column('ts_vector', postgresql.TSVECTOR(), nullable=True),
    sa.Column('name', sa.String(length=300), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('authr_reference', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['object_type_id'], ['ub_object_types.id'], ),
    sa.ForeignKeyConstraint(['owner_id'], ['ub_sa_auth_identities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('native_table', 'native_id', name='ub_functional_objects_c2'),
    sa.UniqueConstraint('object_type_id', 'native_id', name='ub_functional_objects_c1')
    )
    op.create_index(op.f('ix_ub_functional_objects_is_deleted'), 'ub_functional_objects', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_ub_functional_objects_uuid'), 'ub_functional_objects', ['uuid'], unique=True)
    op.create_index('ub_functional_objects_idx_name', 'ub_functional_objects', ['name'], unique=False)
    op.create_index('ub_functional_objects_idx_owner', 'ub_functional_objects', ['owner_id'], unique=False)
    op.create_index('ix_fobj__ts_vector__', 'ub_functional_objects', ['ts_vector'], unique=False, postgresql_using='gin')
    op.create_table('ub_fs_objects',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('full_name', sa.String(length=2048), nullable=True),
    sa.Column('storage_id', sa.BigInteger(), nullable=True),
    sa.Column('parent_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['ub_functional_objects.id'], ),
    sa.ForeignKeyConstraint(['storage_id'], ['ub_fs_storages.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ub_fs_folders',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['ub_fs_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key('fk_fso_parent_folder_id', 'ub_fs_objects', 'ub_fs_folders', ['parent_id'], ['id'], use_alter=True)
    op.create_table('ub_fs_files',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('content_type', sa.String(length=256), nullable=True),
    sa.Column('embedded_content', sa.LargeBinary(), nullable=True),
    sa.Column('content_size', sa.Integer(), nullable=True),
    sa.Column('content_location', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['ub_fs_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ub_hierarchy_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('uuid', uniback.persistence.base.GUID(length=32), nullable=False),
    sa.Column('hierarchy_id', sa.Integer(), nullable=False),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['hierarchy_id'], ['ub_hierarchies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('ub_sa_annotation_form_template_field',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('form_template_id', sa.BigInteger(), nullable=False),
    sa.Column('form_field_id', sa.BigInteger(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['form_field_id'], ['ub_sa_annotation_form_field.id'], ),
    sa.ForeignKeyConstraint(['form_template_id'], ['ub_sa_annotation_form_template.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_template_id', 'rank', name='ub_sa_annotation_form_template_field_c1')
    )
    op.create_table('ub_sa_auth_groups_identities',
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['group_id'], ['ub_sa_auth_groups.id'], ),
    sa.ForeignKeyConstraint(['identity_id'], ['ub_sa_auth_identities.id'], ),
    sa.PrimaryKeyConstraint('group_id', 'identity_id')
    )
    op.create_table('ub_sa_auth_identities_authenticators',
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('authenticator_id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('authenticator_info', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('last_login_time', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['authenticator_id'], ['ub_sa_auth_authenticators.id'], ),
    sa.ForeignKeyConstraint(['identity_id'], ['ub_sa_auth_identities.id'], ),
    sa.PrimaryKeyConstraint('identity_id', 'authenticator_id')
    )
    op.create_index('index_IdentityAuthenticator_on_AuthenticatorInfo_gin', 'ub_sa_auth_identities_authenticators', ['authenticator_info'], unique=False, postgresql_using='gin')
    op.create_table('ub_sa_auth_identity_store_entries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('update_time', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['ub_sa_auth_identities.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('identity_id', 'key', name='ub_sa_auth_identity_store_entries_identity_key')
    )
    op.create_table('ub_sa_auth_organizations_identities',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['ub_sa_auth_identities.id'], ),
    sa.ForeignKeyConstraint(['organization_id'], ['ub_sa_auth_organizations.id'], ),
    sa.PrimaryKeyConstraint('organization_id', 'identity_id')
    )
    op.create_table('ub_sa_auth_permissions_expression',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('acl_id', sa.Integer(), nullable=True),
    sa.Column('expression', sa.String(length=500), nullable=True),
    sa.Column('validity_start', sa.DateTime(), nullable=True),
    sa.Column('validity_end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acl_id'], ['ub_sa_auth_permissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ub_sa_auth_roles_identities',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('identity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['identity_id'], ['ub_sa_auth_identities.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['ub_sa_auth_roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'identity_id')
    )
    op.create_table('ub_sa_browser_filters',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', uniback.persistence.base.GUID(length=32), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('object_type', sa.String(length=80), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['ub_sa_auth_identities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', 'object_type', 'user_id', name='ub_sa_browser_filters_c1'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('ub_fs_fos_in_files',
    sa.Column('file_id', sa.BigInteger(), nullable=False),
    sa.Column('fos_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['file_id'], ['ub_fs_files.id'], ),
    sa.ForeignKeyConstraint(['fos_id'], ['ub_functional_objects.id'], ),
    sa.PrimaryKeyConstraint('file_id', 'fos_id')
    )
    op.create_table('ub_case_studies',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['ub_functional_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ub_collections',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['ub_functional_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ub_datasets',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('structure', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('provenance', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['ub_functional_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ub_geo_grids',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['ub_functional_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ub_geo_layers',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('layer_type', sa.String(length=10), nullable=True),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['ub_datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ub_gui_dashboards',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['ub_functional_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ub_gui_views',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['ub_functional_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ub_hierarchy_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=128), nullable=True),
    sa.Column('uuid', uniback.persistence.base.GUID(length=32), nullable=False),
    sa.Column('hierarchy_id', sa.Integer(), nullable=False),
    sa.Column('parent_node_id', sa.Integer(), nullable=True),
    sa.Column('level_id', sa.Integer(), nullable=True),
    sa.Column('reference_node_id', sa.Integer(), nullable=True),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['hierarchy_id'], ['ub_hierarchies.id'], ),
    sa.ForeignKeyConstraint(['level_id'], ['ub_hierarchy_levels.id'], ),
    sa.ForeignKeyConstraint(['parent_node_id'], ['ub_hierarchy_nodes.id'], ),
    sa.ForeignKeyConstraint(['reference_node_id'], ['ub_hierarchy_nodes.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('ub_sa_annotation_item',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('annotation_type', sa.String(length=80), nullable=True),
    sa.Column('file_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['file_id'], ['ub_fs_files.id'], ),
    sa.ForeignKeyConstraint(['id'], ['ub_functional_objects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ub_sa_annotation_relationship',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('subject_id', sa.BigInteger(), nullable=False),
    sa.Column('object_id', sa.BigInteger(), nullable=False),
    sa.Column('form_rl_id', sa.BigInteger(), nullable=False),
    sa.Column('form_rev_rl_id', sa.BigInteger(), nullable=True),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['form_rev_rl_id'], ['ub_sa_annotation_form_template_field.id'], ),
    sa.ForeignKeyConstraint(['form_rl_id'], ['ub_sa_annotation_form_template_field.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['object_id'], ['ub_functional_objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['subject_id'], ['ub_functional_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('subject_id', 'object_id', 'form_rl_id', name='ub_sa_annotation_relationship_c1')
    )
    op.create_table('ub_sa_auth_permissions_detail',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('acl_id', sa.Integer(), nullable=False),
    sa.Column('acl_expression_id', sa.Integer(), nullable=True),
    sa.Column('authorizable_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.Column('validity_start', sa.DateTime(), nullable=True),
    sa.Column('validity_end', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['acl_expression_id'], ['ub_sa_auth_permissions_expression.id'], ),
    sa.ForeignKeyConstraint(['acl_id'], ['ub_sa_auth_permissions.id'], ),
    sa.ForeignKeyConstraint(['authorizable_id'], ['ub_sa_auth_authorizables.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_id'], ['ub_sa_auth_permission_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ub_case_studies_functional_objects',
    sa.Column('case_study_id', sa.BigInteger(), nullable=False),
    sa.Column('functional_object_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['case_study_id'], ['ub_case_studies.id'], ),
    sa.ForeignKeyConstraint(['functional_object_id'], ['ub_functional_objects.id'], ),
    sa.PrimaryKeyConstraint('case_study_id', 'functional_object_id')
    )
    op.create_table('ub_collections_functional_objects',
    sa.Column('collection_id', sa.BigInteger(), nullable=False),
    sa.Column('functional_object_uuid', uniback.persistence.base.GUID(length=32), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['ub_collections.id'], ),
    sa.ForeignKeyConstraint(['functional_object_uuid'], ['ub_functional_objects.uuid'], ),
    sa.PrimaryKeyConstraint('collection_id', 'functional_object_uuid')
    )
    op.create_table('ub_sa_annotation_field',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('form_field_id', sa.BigInteger(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['form_field_id'], ['ub_sa_annotation_form_field.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id'], ['ub_sa_annotation_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_field_id', 'value', name='ub_sa_annotation_field_c1')
    )
    op.create_table('ub_sa_annotation_item_functional_object',
    sa.Column('annotation_item_id', sa.BigInteger(), nullable=False),
    sa.Column('functional_object_id', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['annotation_item_id'], ['ub_sa_annotation_item.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['functional_object_id'], ['ub_functional_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('annotation_item_id', 'functional_object_id')
    )
    op.create_table('ub_sa_annotation_template',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('form_template_id', sa.BigInteger(), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['form_template_id'], ['ub_sa_annotation_form_template.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id'], ['ub_sa_annotation_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('form_template_id', 'value', name='ub_sa_annotation_template_c1')
    )
    op.create_table('ub_sa_annotation_text',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('value', sa.String(length=4096), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['ub_sa_annotation_item.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_fso_parent_folder_id', 'ub_fs_objects', type_='foreignkey')
    op.drop_table('ub_sa_annotation_text')
    op.drop_table('ub_sa_annotation_template')
    op.drop_table('ub_sa_annotation_item_functional_object')
    op.drop_table('ub_sa_annotation_field')
    op.drop_table('ub_collections_functional_objects')
    op.drop_table('ub_case_studies_functional_objects')
    op.drop_table('ub_sa_auth_permissions_detail')
    op.drop_table('ub_sa_annotation_relationship')
    op.drop_table('ub_sa_annotation_item')
    op.drop_table('ub_hierarchy_nodes')
    op.drop_table('ub_gui_views')
    op.drop_table('ub_gui_dashboards')
    op.drop_table('ub_geo_layers')
    op.drop_table('ub_geo_grids')
    op.drop_table('ub_datasets')
    op.drop_table('ub_collections')
    op.drop_table('ub_case_studies')
    op.drop_table('ub_fs_fos_in_files')
    op.drop_table('ub_sa_browser_filters')
    op.drop_table('ub_sa_auth_roles_identities')
    op.drop_table('ub_sa_auth_permissions_expression')
    op.drop_table('ub_sa_auth_organizations_identities')
    op.drop_table('ub_sa_auth_identity_store_entries')
    op.drop_index('index_IdentityAuthenticator_on_AuthenticatorInfo_gin', table_name='ub_sa_auth_identities_authenticators', postgresql_using='gin')
    op.drop_table('ub_sa_auth_identities_authenticators')
    op.drop_table('ub_sa_auth_groups_identities')
    op.drop_table('ub_sa_annotation_form_template_field')
    op.drop_table('ub_hierarchy_levels')
    op.drop_table('ub_fs_files')
    op.drop_table('ub_fs_folders')
    op.drop_table('ub_fs_objects')
    op.drop_index('ix_fobj__ts_vector__', table_name='ub_functional_objects')
    op.drop_index('ub_functional_objects_idx_owner', table_name='ub_functional_objects')
    op.drop_index('ub_functional_objects_idx_name', table_name='ub_functional_objects')
    op.drop_index(op.f('ix_ub_functional_objects_uuid'), table_name='ub_functional_objects')
    op.drop_index(op.f('ix_ub_functional_objects_is_deleted'), table_name='ub_functional_objects')
    op.drop_table('ub_functional_objects')
    op.drop_table('ub_sa_task_instances')
    op.drop_table('ub_sa_auth_roles')
    op.drop_table('ub_sa_auth_permissions')
    op.drop_table('ub_sa_auth_organizations')
    op.drop_table('ub_sa_auth_obj_types_perm_types')
    op.drop_table('ub_sa_auth_identities')
    op.drop_table('ub_sa_auth_groups')
    op.drop_table('ub_sa_auth_functions_rels')
    op.drop_table('ub_sa_annotation_form_template')
    op.drop_table('ub_sa_annotation_form_item_object_types')
    op.drop_table('ub_sa_annotation_form_field')
    op.drop_table('ub_hierarchies')
    op.drop_table('ub_sa_task_system_processes')
    op.drop_table('ub_sa_task_statuses')
    op.drop_table('ub_sa_auth_permission_types')
    op.drop_table('ub_sa_auth_functions')
    op.drop_table('ub_sa_auth_authorizables')
    op.drop_table('ub_sa_auth_authenticators')
    op.drop_table('ub_sa_annotation_form_item')
    op.drop_table('ub_object_types')
    op.drop_table('ub_hierarchy_types')
    op.drop_table('ub_fs_storages')
    # ### end Alembic commands ###
