"""add_app_flavor_and_menu_entities

Revision ID: 843b6a847b4f
Revises: 80e9cad03427
Create Date: 2026-01-19 10:18:41.228059

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa
import uniback.persistence.base


# revision identifiers, used by Alembic.
revision = '843b6a847b4f'
down_revision = '80e9cad03427'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ub_gui_app_flavors',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('definition', uniback.persistence.base.JSONB(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['ub_functional_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ub_gui_screens',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('screen_type', sa.String(length=50), nullable=True),
    sa.Column('main_entity_type', sa.String(length=100), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('definition', uniback.persistence.base.JSONB(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['ub_functional_objects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ub_gui_menus',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('app_flavor_id', sa.BigInteger(), nullable=True),
    sa.Column('parent_menu_id', sa.BigInteger(), nullable=True),
    sa.Column('screen_id', sa.BigInteger(), nullable=True),
    sa.Column('order', sa.BigInteger(), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('definition', uniback.persistence.base.JSONB(), nullable=True),
    sa.ForeignKeyConstraint(['app_flavor_id'], ['ub_gui_app_flavors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['id'], ['ub_functional_objects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_menu_id'], ['ub_gui_menus.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['screen_id'], ['ub_gui_screens.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ub_gui_menus')
    op.drop_table('ub_gui_screens')
    op.drop_table('ub_gui_app_flavors')
    # ### end Alembic commands ###
