"""add_internationalization_support

Revision ID: deeb676c33a8
Revises: 843b6a847b4f
Create Date: 2026-01-19 10:54:22.532282

"""

from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'deeb676c33a8'
down_revision = '843b6a847b4f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ub_entity_labels',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('language_id', sa.String(length=5), nullable=False),
    sa.Column('entity_type', sa.String(length=8), nullable=False),
    sa.Column('entity_id', sa.String(length=128), nullable=False),
    sa.Column('label', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ub_entity_labels')
    # ### end Alembic commands ###
