"""
Tests for the bulk endpoint generated by ``make_simple_rest_crud``.

The bulk endpoint accepts a list of items, classifies each as
create/update/delete based on the presence of ``id`` and ``_op``, and either
runs each row in its own savepoint (``on_error=partial``, the default) or
aborts the whole batch on the first failure (``on_error=abort``).

Tests use the ``viewz`` entity (``View`` model) because ``FunctionalObject``
auto-excludes ``id``, ``uuid`` and ``creation_time`` from create, leaving a
minimal payload of just ``name``.
"""
from __future__ import annotations

from fastapi.testclient import TestClient


BULK = "/api/viewz/bulk"
LIST = "/api/viewz/"


def _list_names(client: TestClient) -> list[str]:
    body = client.get(LIST).json()
    return [row.get("name") for row in (body.get("content") or [])]


def test_bulk_create_all_valid(logged_in_client: TestClient):
    payload = [
        {"data": {"name": "view-a"}},
        {"data": {"name": "view-b"}},
        {"data": {"name": "view-c"}},
    ]
    r = logged_in_client.post(BULK, json=payload)
    assert r.status_code == 200, r.text
    body = r.json()["content"]

    assert body["summary"] == {"created": 3, "updated": 0, "deleted": 0, "failed": 0}
    assert [res["op"] for res in body["results"]] == ["create"] * 3
    assert all(res["ok"] and res["id"] is not None for res in body["results"])

    names = _list_names(logged_in_client)
    assert {"view-a", "view-b", "view-c"}.issubset(names)


def test_bulk_accepts_flat_rows_without_data_wrapper(logged_in_client: TestClient):
    """A row may carry its fields at the top level (no ``{"data": ...}`` wrap)."""
    r = logged_in_client.post(BULK, json=[{"name": "flat-row"}])
    assert r.status_code == 200, r.text
    assert r.json()["content"]["summary"]["created"] == 1
    assert "flat-row" in _list_names(logged_in_client)


def test_bulk_update_existing(logged_in_client: TestClient):
    created = logged_in_client.post(BULK, json=[
        {"data": {"name": "before-1"}},
        {"data": {"name": "before-2"}},
    ]).json()["content"]
    ids = [res["id"] for res in created["results"]]

    update = [
        {"id": ids[0], "data": {"name": "after-1"}},
        {"id": ids[1], "data": {"name": "after-2"}},
    ]
    r = logged_in_client.post(BULK, json=update)
    assert r.status_code == 200, r.text
    body = r.json()["content"]
    assert body["summary"] == {"created": 0, "updated": 2, "deleted": 0, "failed": 0}

    names = _list_names(logged_in_client)
    assert {"after-1", "after-2"}.issubset(names)
    assert "before-1" not in names and "before-2" not in names


def test_bulk_mixed_create_and_update(logged_in_client: TestClient):
    seed = logged_in_client.post(BULK, json=[{"data": {"name": "keeper"}}]).json()["content"]
    keeper_id = seed["results"][0]["id"]

    r = logged_in_client.post(BULK, json=[
        {"data": {"name": "fresh"}},                      # create
        {"id": keeper_id, "data": {"name": "renamed"}},   # update
    ])
    assert r.status_code == 200, r.text
    body = r.json()["content"]
    assert body["summary"] == {"created": 1, "updated": 1, "deleted": 0, "failed": 0}
    assert body["results"][0]["op"] == "create"
    assert body["results"][1]["op"] == "update"
    assert body["results"][1]["id"] == keeper_id


def test_bulk_delete_op(logged_in_client: TestClient):
    seed = logged_in_client.post(BULK, json=[
        {"data": {"name": "doomed-1"}},
        {"data": {"name": "doomed-2"}},
        {"data": {"name": "survives"}},
    ]).json()["content"]
    ids = [res["id"] for res in seed["results"]]

    r = logged_in_client.post(BULK, json=[
        {"_op": "delete", "id": ids[0]},
        {"_op": "delete", "id": ids[1]},
    ])
    assert r.status_code == 200, r.text
    body = r.json()["content"]
    assert body["summary"] == {"created": 0, "updated": 0, "deleted": 2, "failed": 0}

    names = _list_names(logged_in_client)
    assert "survives" in names
    assert "doomed-1" not in names and "doomed-2" not in names


def test_bulk_partial_mode_failed_row_does_not_block_others(logged_in_client: TestClient):
    """A delete of a missing id fails its savepoint but lets later rows commit."""
    r = logged_in_client.post(BULK, json=[
        {"data": {"name": "ok-1"}},
        {"_op": "delete", "id": 99999},   # not found
        {"data": {"name": "ok-2"}},
    ])
    assert r.status_code == 200, r.text
    body = r.json()["content"]
    assert body["summary"] == {"created": 2, "updated": 0, "deleted": 0, "failed": 1}
    assert body["results"][1]["ok"] is False
    assert body["results"][1]["errors"][0]["type"] == "not_found"

    names = _list_names(logged_in_client)
    assert {"ok-1", "ok-2"}.issubset(names)


def test_bulk_abort_mode_rolls_back_everything(logged_in_client: TestClient):
    r = logged_in_client.post(
        BULK + "?on_error=abort",
        json=[
            {"data": {"name": "abort-1"}},
            {"_op": "delete", "id": 99999},
            {"data": {"name": "abort-2"}},
        ],
    )
    assert r.status_code == 422, r.text
    detail = r.json()
    # FastAPI's HTTPException(detail=...) is wrapped in the error envelope; the
    # original detail dict ends up in the issues' message field. We assert the
    # high-level invariant: nothing got persisted.
    names = _list_names(logged_in_client)
    assert "abort-1" not in names and "abort-2" not in names


def test_bulk_rejects_invalid_on_error(logged_in_client: TestClient):
    r = logged_in_client.post(BULK + "?on_error=lolnope", json=[])
    assert r.status_code == 400


def test_bulk_rejects_non_array_body(logged_in_client: TestClient):
    r = logged_in_client.post(BULK, json={"not": "a list"})
    assert r.status_code == 400


def test_bulk_empty_body_is_a_noop(logged_in_client: TestClient):
    r = logged_in_client.post(BULK, json=[])
    assert r.status_code == 200
    body = r.json()["content"]
    assert body["results"] == []
    assert body["summary"] == {"created": 0, "updated": 0, "deleted": 0, "failed": 0}
